package ui.game_flow;

public enum GameResult {
    PLAYER_WHITE_WON_BY_CHECKMATE,
    PLAYER_BLACK_WON_BY_CHECKMATE,
    PLAYER_WHITE_WON_BY_RESIGNATION,
    PLAYER_BLACK_WON_BY_RESIGNATION,
    PLAYER_WHITE_WON_BY_TIME,
    PLAYER_BLACK_WON_BY_TIME,
    REPETITION_DRAW,
    STALEMATE,
    BOTH_SIDES_AGREED_FOR_A_DRAW
}
