package chessRoot.user_interface.game_flow;

public enum GameStates {
    PLAYER_WHITE_TURN,
    PLAYER_WHITE_SELECTED_PIECE,
    PLAYER_WHITE_RESIGNED,
    PLAYER_WHITE_OFFERED_A_DRAW,
    PLAYER_BLACK_TURN,
    PLAYER_BLACK_SELECTED_PIECE,
    PLAYER_BLACK_RESIGNED,
    PLAYER_BLACK_OFFERED_A_DRAW
}
