package chessRoot.user_interface.game_flow;

public enum GameStates {
    WHITE_TURN,
    WHITE_SELECTED_PIECE,
    WHITE_RESIGNED,
    WHITE_OFFERED_A_DRAW,
    BLACK_TURN,
    BLACK_SELECTED_PIECE,
    BLACK_RESIGNED,
    BLACK_OFFERED_A_DRAW,
    WHITE_PROMOTION,
    BLACK_PROMOTION
}
